- q: TESTING
  a: |  # this bar is required to let the answer span multiple lines.
      Mobile Units are student-run live sound and lights services provided
      by WCPR. If you see our table at a campus event, we're playing music,
      organizing lights, or running sound for the organization running the
      event. <br>
      Mobile Units are another part of what WCPR does, alongside
      other efforts like providing original programming as a radio station,
      recording in our studios, and putting on concerts on campus.

- q: What services does a Mobile Unit provide?
  a: |
      We offer a ton of different sound and light options for whatever
      your organization needs for an event. Find all of them in the
      <a href="#docs">Mobile Units Packages & Prices</a> document.<br>
      If you have any questions about our packages, feel free to email us at
      <a href="mailto:mobileunit@wcpr.org">mobileunit@wcpr.org</a>

- q: How does Mobile Unit pricing work?
  a: |
      Our pricing varies per package and per your needs. Most of our packages
      have a <strong>flat fee</strong> for equipment and setup, and
      any of our staffed packages have an <strong>hourly rate</strong> for
      operating the equipment.<br>
      Equipment set-up and breakdown are not included in the hourly fees.
      <br><br>
      Anything booked within ten days will incur a <strong>late fee</strong>.
      <br>
      Events held off-campus include a <strong>transportation fee</strong>
      for moving equipment.<br>
      Events that run overtime will be charged an <strong>overtime fee</strong>
      <br>
      Any event cancelled less than 48 hours prior to the event will incur
      a <strong>cancellation fee</strong>.
      <br><br>
      <em>An item of note:</em> WCPR staff are student volunteers and are
      not paid for their time. The money you pay goes directly to repairing
      and updating our equipment as it wears and ages.

- q: How do I book a Mobile Unit?
  a: |
      Please fill out the <a href="#booking">Mobile Unit Request form</a>.
      <strong>Until you've submitted that form, we cannot consider your
      event nor can we assess our staff availability.</strong> Keep in mind
      that the closer to your event you submit this, the less likely it is
      for our staff to be available (we are all student volunteers!).
      <br><br>
      Please review our <a href="#docs">Mobile Unit Contract</a> document to find
      detailed information concerning staffing, overtime, and other policies
      in accordance with Mobile Units.

- q: I submitted the form - what happens now?
  a: |
      Great! Our staff will now be coordinating volunteer availability for
      your event. Please allow us until two weeks prior to your event date
      before our response. Once this has happened, you will get an email
      with one of two outcomes:
      <ul>
        <li>
        In the event we have staff available for your event, it will be
        <strong>Approved</strong>. If you have special requests (e.g. a
        certain kind of music you'd like to be played, specific lighting
        arrangements, etc.), do not hesitate to contact us at
        <a href="mailto:mobileunit@wcpr.org">mobileunit@wcpr.org</a>
        <br>
        <strong>Note</strong>: If you have any live artist, band, DJ, etc.
        at your event, <em>coordination is necessary</em> between us, you,
        and your act(s).
        </li>
        <li>
        In the event we do not have staff available for your event, it will
        be <strong>Denied</strong>. Please contact the Office of Student Life
        (10th floor of Howe) for additional options if sound and/or lighting
        services are integral to your event.
        </li>
      </ul>
      We may also reach out before our decision if we need more information
      on the event.

- q: How will the day of the event go?
  a: |
      We will be arriving early to set up our equipment - how early we show
      up depends on the package your organization booked, but in general
      we will arrive at least an hour before the event start time.
      <br><br>
      Following the event, the organization will be billed for WCPR's
      services through coordination between our
      <a href="/contact/#staff_business">Business Manager</a> and the Office
      of Student Life. Contact
      <a href="mailto:business@wcpr.org">business@wcpr.org</a> with any
      billing questions.
      <br><br>
      If you have any additional questions, feel free to reach out to
      <a href="mailto:mobileunit@wcpr.org">mobileunit@wcpr.org</a>
      at any time!